spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/board?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&sslmode=disable
    username: root
    password: 1234

  # ?? ?? ?? ??? ??
  devtools:
    restart:
      enabled: 'false'
    livereload:
      enabled: 'true'


  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: 'false'
    show-sql: 'true'
    open-in-view: 'false'
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        default_batch_fetch_size: '100'